### ISSUE TITLE
SMbios version

### ISSUE THREAD

**Issue by maniacx** [Kingtous/thinkbook14p-Gen2-ACH-hackintosh#5]
Hello Kingtous.
I am new to hackintosh.
My Asus M3401 Viwobook also use the same CPU, iGPU and Wifi .(AMD Ryzen 7 5800H, VEGA8,AX200 WiFi6)

Although it does have nvidia dGPU, GTX3050, but i have disable using  SSDT-dGPU-Off.aml and SSDT-GPU-DISABLE.aml

But I cannot figure out which smbios version to use. Only suggestion I found for AMD from "nootred " is to use **MacBookPro16,3** or **iMac20,1** or **iMacPro1,1**

1. Which SMBIOS did you use?

**Comment by Kingtous** [comment]
MacBookPro16,3
